### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required '/var/www/html/govinfo/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/govinfo/console.php on line 4

### ISSUE THREAD

**Issue by wethepeopleonline** [cnizzardini/gov-info#2]
I like your PHP Script for GovInfo API; I just wish I could get it working. The image demo looks awesome! I appreciate it.

I am needing to download *everything* from GovInfo; dating back to the furthest 1940 entries before I have to tear into PDF files to get the rest.

What can I do to resolve the below error? I am running latest PHP 7.4.x on Debian 11 Bullseye. Thank you in advance!

Best Regards,

Brandon

```
root@VMJail:/var/www/html/govinfo# php console.php collection:packages --file
PHP Warning:  require(/var/www/html/govinfo/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/govinfo/console.php on line 4
PHP Fatal error:  require(): Failed opening required '/var/www/html/govinfo/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/govinfo/console.php on line 4
root@VMJail:/var/www/html/govinfo#
```

**Comment by cnizzardini** [comment]
Well I stopped working on this project and imagine the govinfo api _could've_ changed a bit in the last two years, so you'll want to check that out.

As for your specific issue its strange that this is not in your autoloader. You installed via `composer` right?

**Comment by wethepeopleonline** [comment]
@cnizzardini ,

Thank you for your reply! I imagine you are correct the API could have changed. I did not install anything via "composer"; In fact, I do not know what that is. I installed a Debian Linux LAMP (Apache + MySQL + PHP 7.4.x) and manually ran the command "php console.php collection:packages --file" ; then gave me an error saying /vendor not available (and it's not in your package). Is /vendor a "composer" folder? Is there a way you can share the /vendor folder, so that I can try and run your code in native PHP 7.x / Linux / Apache 2.x ? Thank you for your time! Best Regards, Brandon

**Comment by wethepeopleonline** [comment]
Oh I see! Composer is a PHP Library Pack. I found this link: [https://tecadmin.net/how-to-install-and-use-php-composer-on-debian-11/](url). I hope this provides everything needed! I didn't see the requirement for composer; my apologies for the bother!

**Comment by wethepeopleonline** [comment]
After installing composer; I had to copy the contents into your project folder which I called "govinfo"; I wrote the apiKey.txt with my key inside and then gave permissions to www-data:www-data and was able to run it as a lower user (had to install composer / require [your project]) as super user (non-root wouldn't work); after it pulled down required libraries. Basically installed your package twice (github pull down & composer require) and merged the folder "Vendor" into the github extracted and The following worked (Thank you!):

`brandon@VMJail:/var/www/html/govinfo$ ls -l
total 48
-rw-r--r-- 1 www-data www-data   41 Feb 17 20:36 apiKey.txt
-rw-r--r-- 1 www-data www-data  837 Feb 16 00:40 composer.json
-rw-r--r-- 1 www-data www-data  555 Feb 16 00:40 console.php
drwxr-xr-x 2 www-data www-data 4096 Feb 16 00:40 docs
-rw-r--r-- 1 www-data www-data 1092 Feb 16 00:40 LICENSE.md
-rw-r--r-- 1 www-data www-data 1478 Feb 16 00:40 phpmd.xml
-rw-r--r-- 1 www-data www-data  803 Feb 16 00:40 phpunit.xml
-rw-r--r-- 1 www-data www-data 6982 Feb 16 00:40 README.md
drwxr-xr-x 4 www-data www-data 4096 Feb 16 00:40 src
drwxr-xr-x 4 www-data www-data 4096 Feb 16 00:40 tests
drwxr-xr-x 8 www-data www-data 4096 Feb 17 20:44 vendor
brandon@VMJail:/var/www/html/govinfo$ php console.php collection:packages --file

 // Loading collections...                                                                                              

 Retrieve packages from what collectionCode?:
  [BILLS     ] Congressional Bills
  [BILLSTATUS] Congressional Bill Status
  [BUDGET    ] United States Budget
  [CCAL      ] Congressional Calendars
  [CDIR      ] Congressional Directory
  [CDOC      ] Congressional Documents
  [CFR       ] Code of Federal Regulations
  [CHRG      ] Congressional Hearings
  [COMPS     ] Statutes Compilations
  [CPD       ] Compilation of Presidential Documents
  [CPRT      ] Congressional Committee Prints
  [CREC      ] Congressional Record
  [CRECB     ] Congressional Record (Bound Edition)
  [CRI       ] Congressional Record Index
  [CRPT      ] Congressional Reports
  [CZIC      ] Coastal Zone Information Center
  [ECFR      ] Electronic Code of Federal Regulations
  [ECONI     ] Economic Indicators
  [ERIC      ] Education Reports from ERIC
  [ERP       ] Economic Report of the President
  [FR        ] Federal Register
  [GAOREPORTS] Government Accountability Office Reports and Comptroller General Decisions
  [GOVMAN    ] United States Government Manual
  [GOVPUB    ] Bulk Submission
  [GPO       ] Additional Government Publications
  [HJOURNAL  ] Journal of the House of Representatives
  [HMAN      ] House Rules and Manual
  [HOB       ] History of Bills
  [LSA       ] List of CFR Sections Affected
  [PAI       ] Privacy Act Issuances
  [PLAW      ] Public and Private Laws
  [PPP       ] Public Papers of the Presidents of the United States
  [SERIALSET ] Congressional Serial Set
  [SJOURNAL  ] Journal of the Senate
  [SMAN      ] Senate Manual
  [STATUTE   ] Statutes at Large
  [USCODE    ] United States Code
  [USCOURTS  ] United States Courts Opinions
 > `

Any tips on pulling down everything?

**Comment by wethepeopleonline** [comment]
Regardless of what date I choose (it only writes to a .csv with this month "February 2022"); any idea how to fix this?

`> USCOURTS

 Enter a start date as YYYY-MM-DD [2022-01-01]:
 > 1776-07-04

 // Retrieving packages...                                                                                              

                                                                                                                        
 [OK] Request completed                                                                                                 
                                                                                                                        
      File downloaded to /home/brandon/Downloads/govinfo-uscourts-1645160566.csv`

Seems to happen with all the collections. It won't go anything backwards of the current month.

**Comment by cnizzardini** [comment]
> After installing composer; I had to copy the contents into your project folder which I called "govinfo"; I wrote the apiKey.txt with my key inside and then gave permissions to www-data:www-data and was able to run it as a lower user (had to install composer / require [your project]) as super user (non-root wouldn't work); after it pulled down required libraries. Basically installed your package twice (github pull down & composer require) and merged the folder "Vendor" into the github extracted and The following worked (Thank you!):

This extra step should not be necessary. You can probably just call the CLI from the vendor path. I am guessing here, but something like this:

```console
php vendor/cnizzardini/gov-info/console.php
```

**Comment by cnizzardini** [comment]
As for the other issue, I am not sure, you might want to adjust the code and debug it. I had a whole idea for an application that pulls in house and senate bills and allow people to comment on them line-by-line, but i realized this wouldn't help the country like I wanted because america is in decline and the congress is leading the race to the bottom. So this package was going to drive the data collection portion of that idea, but I lost interest.

You can fork this package and make it your own. Just use the fork sticking out of america's back.

**Comment by cnizzardini** [comment]
Looks like this person created a fork and has worked on it more recently: https://github.com/ElusiveMind/gov-info

**Comment by wethepeopleonline** [comment]
Thank you for your time! Yes; America needs 2/3rds of Congress, both Chambers of actual WE THE PEOPLE (not Corporate shareholders & Traitors) like 100% is now.

Have a good one!
